name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.9.3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  archive: ^3.3.5
  fhir: ^0.9.3
  # fhir:
  #   path: ../fhir
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  mime: ^1.0.3
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.0
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  test: ^1.22.0