name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.6.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  archive: ^3.2.1
  fhir: ^0.6.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  mime: ^1.0.1
  universal_io: ^2.0.4

dev_dependencies:
  analyzer: ^3.3.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  lint: ^1.8.2
  test: ^1.20.1