name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.4.4
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  archive: ^3.1.2
  fhir: ^0.4.6
  freezed_annotation: ^0.14.2
  http: ^0.13.3
  mime: ^1.0.0
  universal_io: ^2.0.4

dev_dependencies:
  analyzer: ^1.7.1
  build_runner: ^2.0.4
  freezed: ^0.14.2
  lint: ^1.5.3
  test: ^1.17.5