name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.9.3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_auth

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  collection: ^1.16.0
  fhir: ^0.9.3
  # fhir:
  #   path: ../fhir
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_web_auth: ^0.5.0
  freezed_annotation: ^2.2.0
  google_sign_in: ^5.4.2
  http: ^0.13.5
  http_parser: ^4.0.2
  jwt_decoder: ^2.0.1
  oauth2: ^2.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.0
  import_sorter: ^4.6.0
  test: ^1.22.0

