name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.9.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_auth

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  # fhir: ^0.9.0
  fhir:
    path: ../fhir
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.4.1
  freezed_annotation: ^2.1.0
  google_sign_in: ^5.4.2
  http: ^0.13.5
  http_parser: ^4.0.1
  jwt_decoder: ^2.0.1
  oauth2: ^2.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  freezed: ^2.1.1
  import_sorter: ^4.6.0
  test: ^1.21.6

