name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.2.0
homepage: https://github.com/MayJuun/fhir/tree/main/fhir_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  dartz: ^0.9.2
  fhir: ^0.2.4
  flutter:
    sdk: flutter
  flutter_appauth: ^0.9.2
  flutter_secure_storage: ^3.3.5
  freezed_annotation: ^0.12.0
  google_sign_in: ^4.5.9
  http: ^0.12.2

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  lint: ^1.2.0
  test: ^1.15.7

assets:
  - assets/