name: fhir_auth
description: A Dart/Flutter package for authorization & authentication, includes SMART on FHIR and Google sign-in
version: 0.6.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_auth

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fhir: ^0.6.0
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.4
  http: ^0.13.4
  oauth2: ^2.0.0
  oauth2_client: ^2.3.2
  universal_html: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  lint: ^1.8.2
  pedantic: ^1.11.1
  test: ^1.20.1

