name: fhir_path
description: FHIRPath navigation and extraction language implemented in pure Dart to be used with base FHIR packages.
version: 0.5.0-4
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fhir: ^0.5.0-1
  petitparser: ^4.2.0

dev_dependencies:
  test: ^1.17.10
