name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.6.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  fhir_yaml: ^0.6.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  yaml: ^3.1.0

dev_dependencies:
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  freezed: ^1.1.1
  test: ^1.20.2
