name: fhir_uscore
description: FHIR library profile for UsCore based on R4. Combines base fhir package, fhir_auth, fhir_bulk, and fhir_at_rest.
version: 0.3.0-nullsafety.6
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.26.0-17.5.pre"

dependencies:
  archive: ^3.1.2
  collection: ^1.15.0
  dartz: ^0.10.0-nullsafety.1
  fhir_yaml: ^0.3.0-nullsafety.0 
  flutter:
    sdk: flutter
  flutter_appauth: ^1.0.0-nullsafety.0
  flutter_secure_storage: ^4.1.0
  freezed_annotation: ^0.14.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  mime: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2
  lint: ^1.5.3
  test: ^1.16.4
