name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.4.4
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fhir: ^0.4.6
  freezed_annotation: ^0.14.2
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  pedantic: ^1.11.0
  test: ^1.17.5


