name: fhir_db
description: A wrapper for Sembast and SQFlite to enable easy, local and secure storage of fhir resources
version: 0.5.0-3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_db

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  encrypt: ^5.0.1
  fhir: ^0.5.0-3
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.5
  sembast: ^3.1.1
  sembast_sqflite: ^2.0.0+1
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3

dev_dependencies:
  test: ^1.18.2