name: fhir_yaml
description: Dart package to format JSON data to YAML. Supports formatting conventions of pubspec files.
version: 0.5.2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_yaml

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  test: ^1.20.0
  yaml: ^3.1.0
