name: fhir_profiles
description: FHIR library for the use of profiles. Will need auth, bulk, and restful requests from those libraries.
version: 0.4.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_profiles

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fhir: ^0.4.6
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  lint: ^1.5.3
  test: ^1.16.4
